{
 "title": "<SERVICE_NAME> (Auto-Deployed)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ok_health_state", "query": "0.0, 1.0, 2.0, 3.0" },
   {
    "name": "sliding_window",
    "query": "1m, 15m, 30m, 1h, 3h, 12h, 1d, 1w, 1M, 3M"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Health Check by Pod",
   "type": "stat",
   "description": "Service States:\n0 = UP, 1 = UNKNOWN, 2 = DEGRADED, 3 = DOWN",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "health_self_state{service_name=\"<SERVICE_NAME>\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Service Health (<= $ok_health_state)",
   "type": "graph",
   "description": "Service States:\n0 = UP, 1 = UNKNOWN, 2 = DEGRADED, 3 = DOWN",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(health_self_state_h_bucket{service_name=\"<SERVICE_NAME>\", le=\"${ok_health_state}\"}[$__rate_interval])) / \nsum (rate(health_self_state_h_count{service_name=\"<SERVICE_NAME>\"}[$__rate_interval]))",
     "legendFormat": "Health ${__from:date:iso} to ${__to:date:iso}"
    }
   ]
  },
  {
   "title": "Critical Dependency Health",
   "type": "stat",
   "description": "Service States:\n0 = UP, 1 = UNKNOWN, 2 = DEGRADED, 3 = DOWN",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod, health_check_name) (health_dependency_state{service_name=\"<SERVICE_NAME>\", health_check_type=\"DEPENDENCY_CRITICAL\"})",
     "legendFormat": "{{health_check_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Service Health (<= $ok_health_state) Avg Over $sliding_window Sliding Window",
   "type": "graph",
   "description": "Service States:\n0 = UP, 1 = UNKNOWN, 2 = DEGRADED, 3 = DOWN",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(health_self_state_h_bucket{service_name=\"<SERVICE_NAME>\", le=\"${ok_health_state}\"}[$sliding_window])) / \nsum (rate(health_self_state_h_count{service_name=\"<SERVICE_NAME>\"}[$sliding_window]))",
     "legendFormat": "Health ${__from:date:iso} to ${__to:date:iso}"
    }
   ]
  },
  {
   "title": "Optional Dependency Health",
   "type": "stat",
   "description": "Service States:\n0 = UP, 1 = UNKNOWN, 2 = DEGRADED, 3 = DOWN",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod, health_check_name) (health_dependency_state{service_name=\"<SERVICE_NAME>\", health_check_type=\"DEPENDENCY_OPTIONAL\"})",
     "legendFormat": "{{health_check_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Service Health Check",
   "type": "graph",
   "description": "Service States:\n0 = UP, 1 = UNKNOWN, 2 = DEGRADED, 3 = DOWN",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "health_self_state{service_name=\"<SERVICE_NAME>\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    flask_http_request_duration_seconds_sum{service_name=\"<SERVICE_NAME>\"}\n    [5m]\n  )\n)\n\nby\n\n(path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Dependencies Health Check",
   "type": "graph",
   "description": "Service States:\n0 = UP, 1 = UNKNOWN, 2 = DEGRADED, 3 = DOWN",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, health_check_name) ( health_dependency_state{service_name=\"<SERVICE_NAME>\"} )",
     "legendFormat": "{{health_check_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Health Check Duration by Dependency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (health_check_name, pod) (health_dependency_duration{service_name=\"<SERVICE_NAME>\"})",
     "legendFormat": "{{health_check_name}} - {{pod}}"
    }
   ]
  }
 ]
}